version: '3.5'
services:
#  proposta-app:
#    image: oi
#    environment:
#      spring.profiles.active: prod
#    depends_on:
#      - rabbit-mq
#      - db
#    ports:
#      - "8080:8080"
  rabbit-mq:
    image: rabbitmq:3-management
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proposal-db